## Random hash Generator

In [4]:
import random
import string
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.section import WD_SECTION
import pandas as pd

# Create a new Word document
doc = Document()
dic_of_hashes = {}

# Set page size to A4 and margin size to 1 inch
section = doc.sections[0]
section.start_type
section.start_type
section.page_height = Pt(11 * 72)
section.page_width = Pt(8.5 * 72)
section.left_margin = Pt(1 * 72)
section.right_margin = Pt(1 * 72)
section.top_margin = Pt(1 * 72)
section.bottom_margin = Pt(1 * 72)

# Number of random strings to generate and save
num_strings = 120

# indicate the number of the quiz
quiz_number = 6

for i in range(num_strings):
    # Generate a random string of length 10
    random_number = random.randint(10000,99999)
    random_number = str(random_number)

    # Add the string to a new page
    doc.add_section(WD_SECTION.NEW_PAGE)
    paragraph = doc.add_paragraph(random_number)

    # Center-align the text on the page
    paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    dic_of_hashes[i] = random_number

# Save the Word document
doc.save(f"quiz_{quiz_number}_tokens.docx")

# save hashes to csv file to compare the keys against students' input after the quiz
df = pd.DataFrame(dic_of_hashes, index = [0]).transpose()
df.columns = ['token']
df.to_csv(f"quiz_{quiz_number}_tokens.csv")

In [5]:

df

     token
0    58119
1    26039
2    34745
3    76759
4    48105
..     ...
115  81882
116  87283
117  64997
118  40281
119  89941

[120 rows x 1 columns]